# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.13
    - name: Install uv
      run: |
        python -m pip install uv
    - name: Publish Package
      env:
        UV_PUBLISH_USERNAME: ${{ secrets.PYPI_USERNAME }}
        UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        uv build
        uv publish
